#This file was generated by "bin/rails generate controller threat name contact severity preview display"
class ThreatController < ApplicationController
  def name
  end

  def contact
  end

  def severity
  end

  def preview
  end

  def display
  end
end
